# .github/workflows/cd.yml
name: Simple Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [self-hosted, vm-lab]

    steps:
      - uses: actions/checkout@v4
      
      # Install deps into a persistent venv
      - name: Install dependencies
        run: |
          python3 -m venv /opt/store-manager/venv
          /opt/store-manager/venv/bin/pip install --upgrade pip wheel
          if [ -f /opt/store-manager/requirements.txt ]; then
            /opt/store-manager/venv/bin/pip install -r /opt/store-manager/requirements.txt
          fi

      # Create environment config for deployment
      - name: Setup environment
        run: |
          cat > /opt/store-manager/.env <<'EOF'
          MYSQL_HOST=localhost
          MONGODB_HOST=localhost
          MYSQL_DB_NAME=mydb
          DB_USERNAME=user
          DB_PASSWORD=pass
          EOF
          chmod 600 /opt/store-manager/.env

      # Create a simple runner script for the deployment
      - name: Create runner script
        run: |
          cat > /opt/store-manager/run.sh <<'EOF'
          #!/bin/bash
          cd /opt/store-manager
          source venv/bin/activate
          python store_manager.py
          EOF
          chmod +x /opt/store-manager/run.sh

      # Test that the deployment works
      - name: Smoke test deployment
        run: |
          cd /opt/store-manager
          source venv/bin/activate
          timeout 10s python store_manager.py || echo "App started successfully"
