name: Simple Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: [self-hosted, vm-lab]
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy dir
        run: |
          mkdir -p /home/gha-runner/store-manager
          rsync -av --delete ./ /home/gha-runner/store-manager/

      - name: Python venv + deps
        run: |
          python3 -m venv /home/gha-runner/store-manager/venv
          /home/gha-runner/store-manager/venv/bin/pip install --upgrade pip wheel
          if [ -f /home/gha-runner/store-manager/requirements.txt ]; then
            /home/gha-runner/store-manager/venv/bin/pip install -r /home/gha-runner/store-manager/requirements.txt
          fi

      - name: Write .env (example; replace with secrets)
        run: |
          cat > /home/gha-runner/store-manager/.env <<'EOF'
          MYSQL_HOST=localhost
          MONGODB_HOST=localhost
          MYSQL_DB_NAME=mydb
          DB_USERNAME=user
          DB_PASSWORD=pass
          EOF
          chmod 600 /home/gha-runner/store-manager/.env