name: Store Manager CI

on: [push, pull_request]

jobs:
  test:
    # 👇 target your org self-hosted runner
    runs-on: [self-hosted, linux, vm-lab]

    # 👇 run steps inside a container so we can apt-get tools as root
    container:
      image: python:3.11-bullseye

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        # No need to publish ports on self-hosted; jobs can reach the service by name
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongodb:
        image: mongo:6
        env:
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: pass
        options: >-
          --health-cmd="mongosh --username user --password pass --host 127.0.0.1 --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Install MySQL client (inside job container)
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y default-mysql-client

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create .env file
        run: |
          # use service DNS names instead of localhost
          echo "MYSQL_HOST=mysql" >> .env
          echo "MONGODB_HOST=mongodb" >> .env
          echo "MYSQL_DB_NAME=mydb" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=pass" >> .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for MySQL to be ready
        env:
          MYSQL_PWD: pass
        run: |
          until mysqladmin ping -hmysql -u"user" --silent; do
            echo 'Waiting for MySQL...'
            sleep 2
          done
          echo 'MySQL is ready!'

      - name: Initialize database
        run: |
          # If your init SQL path is different, adjust it here:
          mysql -hmysql -uuser -ppass mydb < db-init/init.sql

      - name: Run tests
        run: |
          python -m pytest src/tests/ -v --tb=short

      - name: Run application smoke test
        run: |
          # app can still read .env created above
          timeout 10s python src/store_manager.py || true
